version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    container_name: backend-container
    depends_on:
      - postgres


volumes:
  db:
    driver: local
